name: word_game_server
description: A simple command-line application.
version: 0.7.0
publish_to: 'none'

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  common:
      path: ../common/

  bloc: ^8.0.2
  dart_dotenv: ^1.0.1
  dbcrypt: ^2.0.0
  get_it: ^8.0.2
  jaguar_jwt: ^3.0.0
  mongo_dart: ^0.10.3
  rxdart: ^0.28.0
  shelf: ^1.4.2
  shelf_cors_headers: ^0.1.2
  shelf_router: ^1.1.2
  shelf_web_socket: ^2.0.0
  uuid: ^4.5.1
  validators: ^3.0.0
  web_socket_channel: ^3.0.1
  yaml: ^3.1.0

dev_dependencies:
  lints: ^2.0.1
