name: common
description: Common code shared between app and backend
version: 0.4.0
publish_to: 'none'

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  copy_with_extension: ^5.0.4
  equatable: ^2.0.3
  mongo_dart: ^0.10.3
  validators: ^3.0.0

dev_dependencies:
  build_runner: ^2.1.7
  copy_with_extension_gen: ^5.0.4
  lints: ^2.1.1
  test: ^1.25.8
